apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloapp-v2
    track: canary
  name: helloapp-v2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      app: helloapp-v2
      track: canary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloapp-v2
        track: canary
    spec:
      containers:
      - image: 240796/canary-version:v1
        imagePullPolicy: Always
        name: canary-version
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
