apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-v2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloapp
        version: v2
        track: canary
    spec:
      containers:
      - image: 240796/helloapp:v2
        imagePullPolicy: Always
        name: helloapp-v2
      restartPolicy: Always
